### ISSUE TITLE
Payloads from NodeJS not appearing on Messages screen

### ISSUE THREAD

**Issue by robomeister** [IBM/event-streams#12]
Browser Version: 5.0 (Windows)
IBM Event Streams Version: IBM Event Streams Community Edition-2018.3.1
IBM Cloud Private Version: 3.1.1

Hi there.  I have the latest event streams installed on ICP 3.1.1.  I have two clients, one Java and one NodeJS that can both successfully attach and post messages.

The problem that I am having is that messages posted from the Java client appear in the messages console, while ones posted from NodeJS don't.  

In the following screenshot:
![image](https://user-images.githubusercontent.com/10588423/49391643-3f5b3900-f6fa-11e8-854f-8715dc9130da.png)

The message at offsets 2 and 3 appear, which were from a Java client.  Messages 0 and 1, which were from my NodeJS client, don't appear.  However, if I search on the specific offset, then the message is indeed visible:

![image](https://user-images.githubusercontent.com/10588423/49391720-7598b880-f6fa-11e8-9dc2-36f88de7efab.png)

As far as I can tell, my Java code sends the same stringified payload as NodeJS:

![image](https://user-images.githubusercontent.com/10588423/49391871-d9bb7c80-f6fa-11e8-91f7-e5aa67e8e6d0.png)

![image](https://user-images.githubusercontent.com/10588423/49391919-ffe11c80-f6fa-11e8-93dd-8cdd4694a858.png)

**Comment by robomeister** [comment]
Here's the NodeJS client sample, scrubbed of security info:

[sample.js.txt](https://github.com/IBM/event-streams/files/2640659/sample.js.txt)

**Comment by EmmaHumber** [comment]
Hi @robomeister 

From looking at the flows going to Kafka we can see that the protocol used by the NodeJS client is quite back-level - the request headers are at API version 2.

A Kafka client and Kafka broker negotiate to the highest API version supported by both the client and server, in this case v2:
http://kafka.apache.org/protocol.html#protocol_compatibility

The clients section of our pre-requisite page states that Kafka version 2.0 or later clients are supported:
https://ibm.github.io/event-streams/installing/prerequisites/

Unfortunately there's no clear Kafka documentation that links the request APIs versions to the version of Kafka they were added in, but I can see that v1.0 of Kafka was at API v5, so API v2 is quite back level:
https://github.com/apache/kafka/blob/1.0/clients/src/main/java/org/apache/kafka/common/requests/ProduceRequest.java

Kafka should deal with back level clients OK, but we know for example, that the Event Streams message browser does not in some cases, and this is due to the back level protocol.

Our guidance is to use clients based on librdkafka, and the node client for this is node-rdkafka.

I hope that helps, let me know if you need any further information.

**Comment by robomeister** [comment]
Hi Emma, thanks.  I'll give it a shot.  The kafka-node library I've been using was the first one to turn up in a Google search, and seems to have quite a bit more downloads than node-rdkafka.  It may be prudent to back-port in some support for it.

**Comment by robomeister** [comment]
Is there a working sample of a Nodejs application using node-rdkafka?  I'm having a heck of a time with the sasl/ssl settings.

**Comment by robomeister** [comment]
Quack!  This connection string worked:

var consumer = new kafka.KafkaConsumer({
  'group.id': 'kafka',
  'metadata.broker.list': broker,
  'security.protocol' : 'sasl_ssl',
  'ssl.ca.location': require('path').resolve("eventstreams.pem"),
  'sasl.mechanisms' : 'PLAIN',
  'sasl.username' : 'token',
  'sasl.password' : apiKey
});

I was using 'ssl.certificate.location' instead of 'ssl.ca.location'

**Comment by EmmaHumber** [comment]
Glad to hear you got it working.  

I'll feed back to our docs team and see if this is something we can look at including some info on.

**Comment by robomeister** [comment]
Hi Emma, I got my client application working fine using node-rdkafka.  I did want to highlight some client behaviour, though, in case it comes up with others.  In my logs, the following error is occasionally thrown:

{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }

Sometimes when this happens, the client manages to recover and keep receiving messages.  Ultimately, however, the error gets thrown and the client stops working.  I've had to implement the following code to keep the connection active:

consumer.on('event.error', function(err) 
{
   console.log(err);
   consumer.disconnect();
});
consumer.on('disconnected', function(data)
{
   console.log("Disconnected.  Reconnecting...");
   consumer.connect();
});

I don't think this is necessarily an issue with eventstreams, but it is a behaviour at the current levels of the nodejs client and eventstreams.

**Comment by robomeister** [comment]
Hi Emma,
What's the best way to generate/extract these logs?

**Comment by EmmaHumber** [comment]
Hi

Sorry for the delay, I was out of the office.  

There's something slightly odd in the logs.  Two of the brokers show:

2018-12-03 15:58:09,770] ERROR [MetadataCache brokerId=0] Listeners are not identical across brokers: Map(2 -> Map(ListenerName(INTERNAL_SECURE) -> kafka-ibm-es-kafka-sts-2.kafka-ibm-es-kafka-headless-svc.kafka.svc.cluster.local:8084 (id: 2 rack: null), ListenerName(INTERNAL) -> kafka-ibm-es-kafka-sts-2.kafka-ibm-es-kafka-headless-svc.kafka.svc.cluster.local:9092 (id: 2 rack: null)), 1 -> Map(ListenerName(INTERNAL_SECURE) -> kafka-ibm-es-kafka-sts-1.kafka-ibm-es-kafka-headless-svc.kafka.svc.cluster.local:8084 (id: 1 rack: null), ListenerName(EXTERNAL) -> icp31.robobob.ca:31948 (id: 1 rack: null), ListenerName(INTERNAL) -> kafka-ibm-es-kafka-sts-1.kafka-ibm-es-kafka-headless-svc.kafka.svc.cluster.local:9092 (id: 1 rack: null)), 0 -> Map(ListenerName(INTERNAL_SECURE) -> kafka-ibm-es-kafka-sts-0.kafka-ibm-es-kafka-headless-svc.kafka.svc.cluster.local:8084 (id: 0 rack: null), ListenerName(INTERNAL) -> kafka-ibm-es-kafka-sts-0.kafka-ibm-es-kafka-headless-svc.kafka.svc.cluster.local:9092 (id: 0 rack: null))) (kafka.server.MetadataCache)

We've only seen this in pre-release versions of Event Streams, and thought we'd resolved it in our main release - in theory it is likely to prevent messages being processed at all.  Can you confirm which version of Event Streams you are using, and where you downloaded installed it from please?

A `kubectl get pods -o yaml | grep 2018` should give a precise release version string 



With regards to the disconnects, I think I'll need to see concurrent client and server side logs, and an example timestamp of the error being seen to work towards understanding what's going on.

Client side logging : 

We tend to set `debug: all` in the consumer options when using node-rdkafka.  It's noisy, but it depends how long you are running for before you hit the issue as to whether that's a problem - I'm happy to look through lots of logs.  
Unfortunately debug:all doesn't log timestamps so it's difficult to tie up the logs to what's going on at the Kafka side at that time.  Are you able to add a timestamp to your application logging that writes out when the disconnect happens, so that we can match that time to the equivalent in the Kafka logs?

Server side logs:
As before please, just make sure they cover the same time period as the client side logs and that the error has occurred.

Thanks!

**Comment by robomeister** [comment]
Hi Emma, I'll set it up.  

Here's the output of the get pods:
![kafka-get-pods](https://user-images.githubusercontent.com/10588423/50021992-cd5fdb00-ffa8-11e8-9196-2380e9a9992f.png)

And here's the helm chart:
![kafka-helm-chart](https://user-images.githubusercontent.com/10588423/50022012-dcdf2400-ffa8-11e8-936d-4841f3f4f10e.png)

I've also attempted the same client against an IBM Cloud Eventstreams instance, and I get similar behaviour.

**Comment by robomeister** [comment]
Just emailed you the logs

**Comment by EmmaHumber** [comment]
Hi Rob

As discussed via email a while back, the next action was to ensure that the Node.js application restarted the consume by including the following in the error callback

consumer.on('event.error', function(err) {
  console.log("Error: ");
  console.log(err);
  consumer.consume();
}) ;

I'm just tidying up our issues - do you mind if I close this one off, as I've not heard back that the problem is still happening.

Feel free to re-open if it doesn't resolve the problem.


Thanks
Emma
